import type { RequestCategoryDto } from './types'

export const tableHeader = () => [
  {
    key: 'name',
    label: 'اسم الفئة',
    sortable: true,
  },
  {
    key: 'code',
    label: 'الرمز',
    sortable: true,
  },
  {
    key: 'description',
    label: 'الوصف',
    sortable: false,
  },
  {
    key: 'colorCode',
    label: 'اللون',
    sortable: false,
  },
  {
    key: 'iconClass',
    label: 'الأيقونة',
    sortable: false,
  },
  {
    key: 'displayOrder',
    label: 'ترتيب العرض',
    sortable: true,
  },
  {
    key: 'requestTypeCount',
    label: 'عدد الأنواع',
    sortable: true,
  },
  {
    key: 'isEnabled',
    label: 'الحالة',
    sortable: true,
  },
  {
    key: 'actions',
    label: 'الإجراءات',
    sortable: false,
  },
]

export const fakeData: RequestCategoryDto[] = [
  {
    id: 1,
    name: 'طلبات الإجازات',
    description: 'جميع أنواع طلبات الإجازات والوقت الإضافي',
    code: 'LEAVE',
    colorCode: '#4CAF50',
    iconClass: 'fas fa-calendar-alt',
    displayOrder: 1,
    isEnabled: true,
    requestTypeCount: 5,
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-03-20T14:45:00Z',
    isActive: true,
  },
  {
    id: 2,
    name: 'طلبات التدريب',
    description: 'طلبات التدريب والتطوير المهني',
    code: 'TRAINING',
    colorCode: '#2196F3',
    iconClass: 'fas fa-graduation-cap',
    displayOrder: 2,
    isEnabled: true,
    requestTypeCount: 3,
    createdAt: '2024-01-20T09:15:00Z',
    updatedAt: '2024-03-18T11:30:00Z',
    isActive: true,
  },
  {
    id: 3,
    name: 'طلبات المعدات',
    description: 'طلبات المعدات والمستلزمات',
    code: 'EQUIPMENT',
    colorCode: '#FF9800',
    iconClass: 'fas fa-tools',
    displayOrder: 3,
    isEnabled: true,
    requestTypeCount: 7,
    createdAt: '2024-02-01T14:20:00Z',
    updatedAt: '2024-03-15T16:45:00Z',
    isActive: true,
  },
  {
    id: 4,
    name: 'طلبات الموارد البشرية',
    description: 'طلبات متعلقة بالموارد البشرية والشؤون الإدارية',
    code: 'HR',
    colorCode: '#9C27B0',
    iconClass: 'fas fa-users',
    displayOrder: 4,
    isEnabled: false,
    requestTypeCount: 2,
    createdAt: '2024-02-10T08:45:00Z',
    updatedAt: '2024-03-10T13:20:00Z',
    isActive: true,
  },
  {
    id: 5,
    name: 'طلبات تقنية المعلومات',
    description: 'طلبات الدعم التقني وتقنية المعلومات',
    code: 'IT',
    colorCode: '#607D8B',
    iconClass: 'fas fa-laptop',
    displayOrder: 5,
    isEnabled: true,
    requestTypeCount: 8,
    createdAt: '2024-02-15T12:30:00Z',
    updatedAt: '2024-03-12T10:15:00Z',
    isActive: true,
  },
]
