import type { ApprovalChainDto } from './types'

export const tableHeader = () => [
  {
    key: 'name',
    label: 'اسم السلسلة',
    sortable: true,
  },
  {
    key: 'requestType',
    label: 'نوع الطلب',
    sortable: true,
  },
  {
    key: 'department',
    label: 'القسم',
    sortable: true,
  },
  {
    key: 'priority',
    label: 'الأولوية',
    sortable: true,
  },
  {
    key: 'stepsCount',
    label: 'عدد الخطوات',
    sortable: false,
  },
  {
    key: 'maxCompletionHours',
    label: 'الحد الأقصى (ساعة)',
    sortable: true,
  },
  {
    key: 'isActive',
    label: 'الحالة',
    sortable: true,
  },
  {
    key: 'actions',
    label: 'الإجراءات',
    sortable: false,
  },
]

export const fakeData: ApprovalChainDto[] = [
  {
    id: 1,
    requestTypeId: 1,
    requestType: {
      id: 1,
      name: 'إجازة سنوية',
      code: 'ANNUAL_LEAVE',
    },
    departmentId: 1,
    department: {
      id: 1,
      name: 'الهندسة',
      code: 'ENG',
    },
    name: 'موافقة الإجازة السنوية - الهندسة',
    description: 'عملية الموافقة القياسية لطلبات الإجازة السنوية في قسم الهندسة',
    isActive: true,
    priority: 1,
    activationConditions: '{"minDays": 5}',
    allowsParallelApproval: false,
    allowsStepSkipping: true,
    maxCompletionHours: 72,
    timeoutAction: 'Escalate',
    escalationUserId: 10,
    escalationUser: {
      id: 10,
      username: 'hr.manager',
      email: 'hr.manager@company.com',
      name: 'مدير الموارد البشرية',
    },
    approvalSteps: [
      {
        id: 1,
        approvalChainId: 1,
        name: 'موافقة المدير المباشر',
        description: 'موافقة من المدير المباشر للموظف',
        stepOrder: 1,
        isRequired: true,
        allowsAutoApproval: false,
        allowsParallelApproval: false,
        minRequiredApprovals: 1,
        requiresAllApprovers: false,
        maxCompletionHours: 24,
        sendReminders: true,
        firstReminderHours: 12,
        reminderIntervalHours: 6,
        maxReminders: 3,
        timeoutAction: 'Escalate',
        escalationUserId: 15,
        isActive: true,
        createdAt: '2024-01-15T10:30:00Z',
        updatedAt: '2024-03-20T14:45:00Z',
      },
      {
        id: 2,
        approvalChainId: 1,
        name: 'موافقة الموارد البشرية',
        description: 'موافقة نهائية من قسم الموارد البشرية',
        stepOrder: 2,
        isRequired: true,
        allowsAutoApproval: false,
        allowsParallelApproval: false,
        minRequiredApprovals: 1,
        requiresAllApprovers: false,
        maxCompletionHours: 48,
        sendReminders: true,
        firstReminderHours: 24,
        reminderIntervalHours: 12,
        maxReminders: 2,
        timeoutAction: 'AutoReject',
        isActive: true,
        createdAt: '2024-01-15T10:30:00Z',
        updatedAt: '2024-03-20T14:45:00Z',
      },
    ],
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-03-20T14:45:00Z',
  },
  {
    id: 2,
    requestTypeId: 2,
    requestType: {
      id: 2,
      name: 'إجازة مرضية',
      code: 'SICK_LEAVE',
    },
    departmentId: 2,
    department: {
      id: 2,
      name: 'المبيعات',
      code: 'SALES',
    },
    name: 'موافقة الإجازة المرضية - المبيعات',
    description: 'عملية موافقة سريعة للإجازات المرضية',
    isActive: true,
    priority: 2,
    activationConditions: '{"maxDays": 3}',
    allowsParallelApproval: false,
    allowsStepSkipping: false,
    maxCompletionHours: 24,
    timeoutAction: 'AutoApprove',
    approvalSteps: [
      {
        id: 3,
        approvalChainId: 2,
        name: 'موافقة مدير المبيعات',
        description: 'موافقة من مدير قسم المبيعات',
        stepOrder: 1,
        isRequired: true,
        allowsAutoApproval: true,
        allowsParallelApproval: false,
        minRequiredApprovals: 1,
        requiresAllApprovers: false,
        maxCompletionHours: 12,
        sendReminders: true,
        firstReminderHours: 6,
        reminderIntervalHours: 3,
        maxReminders: 2,
        timeoutAction: 'AutoApprove',
        createdAt: '2024-01-20T10:30:00Z',
        updatedAt: '2024-03-18T14:45:00Z',
        isActive: true,
      },
    ],
    createdAt: '2024-01-20T10:30:00Z',
    updatedAt: '2024-03-18T14:45:00Z',
  },
  {
    id: 3,
    requestTypeId: 3,
    requestType: {
      id: 3,
      name: 'طلب عمل إضافي',
      code: 'OVERTIME',
    },
    departmentId: 1,
    department: {
      id: 1,
      name: 'الهندسة',
      code: 'ENG',
    },
    name: 'موافقة العمل الإضافي - الهندسة',
    description: 'عملية موافقة للعمل الإضافي مع موافقة متوازية',
    isActive: true,
    priority: 1,
    allowsParallelApproval: true,
    allowsStepSkipping: false,
    maxCompletionHours: 48,
    timeoutAction: 'AutoReject',
    approvalSteps: [
      {
        id: 4,
        approvalChainId: 3,
        name: 'موافقة المدير والمشرف',
        description: 'موافقة متوازية من المدير والمشرف',
        stepOrder: 1,
        isRequired: true,
        allowsAutoApproval: false,
        allowsParallelApproval: true,
        minRequiredApprovals: 2,
        requiresAllApprovers: true,
        maxCompletionHours: 24,
        sendReminders: true,
        firstReminderHours: 12,
        reminderIntervalHours: 6,
        maxReminders: 3,
        timeoutAction: 'AutoReject',
        isActive: true,
        createdAt: '2024-02-01T10:30:00Z',
        updatedAt: '2024-03-15T14:45:00Z',
      },
      {
        id: 5,
        approvalChainId: 3,
        name: 'موافقة الموارد البشرية',
        description: 'موافقة نهائية من الموارد البشرية للعمل الإضافي',
        stepOrder: 2,
        isRequired: true,
        allowsAutoApproval: false,
        allowsParallelApproval: false,
        minRequiredApprovals: 1,
        requiresAllApprovers: false,
        maxCompletionHours: 24,
        sendReminders: true,
        firstReminderHours: 12,
        reminderIntervalHours: 6,
        maxReminders: 2,
        timeoutAction: 'AutoReject',
        createdAt: '2024-02-01T10:30:00Z',
        updatedAt: '2024-03-15T14:45:00Z',
        isActive: true,
      },
    ],
    createdAt: '2024-02-01T10:30:00Z',
    updatedAt: '2024-03-15T14:45:00Z',
  },
  {
    id: 4,
    requestTypeId: 4,
    requestType: {
      id: 4,
      name: 'طلب تدريب',
      code: 'TRAINING_REQUEST',
    },
    departmentId: 3,
    department: {
      id: 3,
      name: 'التسويق',
      code: 'MKT',
    },
    name: 'موافقة طلبات التدريب - التسويق',
    description: 'عملية موافقة شاملة لطلبات التدريب والتطوير',
    isActive: false,
    priority: 3,
    activationConditions: '{"minCost": 5000}',
    allowsParallelApproval: false,
    allowsStepSkipping: true,
    maxCompletionHours: 120,
    timeoutAction: 'Notify',
    escalationUserId: 20,
    escalationUser: {
      id: 20,
      username: 'training.manager',
      email: 'training.manager@company.com',
      name: 'مدير التدريب',
    },
    approvalSteps: [
      {
        id: 6,
        approvalChainId: 4,
        name: 'موافقة مدير التسويق',
        description: 'موافقة أولية من مدير قسم التسويق',
        stepOrder: 1,
        isRequired: true,
        allowsAutoApproval: false,
        allowsParallelApproval: false,
        minRequiredApprovals: 1,
        requiresAllApprovers: false,
        maxCompletionHours: 48,
        sendReminders: true,
        firstReminderHours: 24,
        reminderIntervalHours: 12,
        maxReminders: 2,
        timeoutAction: 'Escalate',
        escalationUserId: 20,
        createdAt: '2024-02-10T10:30:00Z',
        updatedAt: '2024-03-10T14:45:00Z',
        isActive: true,
      },
      {
        id: 7,
        approvalChainId: 4,
        name: 'موافقة مدير التدريب',
        description: 'تقييم وموافقة من مدير التدريب',
        stepOrder: 2,
        isRequired: true,
        allowsAutoApproval: false,
        allowsParallelApproval: false,
        minRequiredApprovals: 1,
        requiresAllApprovers: false,
        maxCompletionHours: 72,
        sendReminders: true,
        firstReminderHours: 36,
        reminderIntervalHours: 18,
        maxReminders: 2,
        timeoutAction: 'Notify',
        isActive: true,
        createdAt: '2024-02-10T10:30:00Z',
        updatedAt: '2024-03-10T14:45:00Z',
      },
    ],
    createdAt: '2024-02-10T10:30:00Z',
    updatedAt: '2024-03-10T14:45:00Z',
  },
]
