import type { TableHeader } from '~/components/app-table/types'
import type { TopicDto } from './types'
import { fakeData as subjects } from '../subjects'
export const tableHeader = (t: (key: string) => string) => {
  return [
    {
      key: 'name',
      label: t('topic-name'),
    },
    {
      key: 'subjectName',
      label: t('subject-name'),
    },
    {
      key: 'actions',
      label: t('actions'),
    },
  ]
}
// Expanded fake data for topics
export const fakeData: TopicDto[] = [
  {
    id: '1',
    name: 'Mechanics',
    deleted: false,
    creationDate: '',
    subject: subjects[0],
    subjectId: subjects[0].id,
    subjectName: subjects[0].name,
  },
  {
    id: '2',
    name: 'Thermodynamics',
    deleted: false,
    creationDate: '',
    subject: subjects[0],
    subjectId: subjects[0].id,
    subjectName: subjects[0].name,
  },
  {
    id: '3',
    name: 'Optics',
    deleted: false,
    creationDate: '',
    subject: subjects[0],
    subjectId: subjects[0].id,
    subjectName: subjects[0].name,
  },
  {
    id: '4',
    name: 'Quantum Mechanics',
    deleted: false,
    creationDate: '',
    subject: subjects[0],
    subjectId: subjects[0].id,
    subjectName: subjects[0].name,
  },
  {
    id: '5',
    name: 'Algebra',
    deleted: false,
    creationDate: '',
    subject: subjects[1],
    subjectId: subjects[1].id,
    subjectName: subjects[1].name,
  },
  {
    id: '6',
    name: 'Geometry',
    deleted: false,
    creationDate: '',
    subject: subjects[1],
    subjectId: subjects[1].id,
    subjectName: subjects[1].name,
  },
  {
    id: '7',
    name: 'Trigonometry',
    deleted: false,
    creationDate: '',
    subject: subjects[1],
    subjectId: subjects[1].id,
    subjectName: subjects[1].name,
  },
  {
    id: '8',
    name: 'Calculus',
    deleted: false,
    creationDate: '',
    subject: subjects[1],
    subjectId: subjects[1].id,
    subjectName: subjects[1].name,
  },
  {
    id: '9',
    name: 'Organic Chemistry',
    deleted: false,
    creationDate: '',
    subject: subjects[2],
    subjectId: subjects[2].id,
    subjectName: subjects[2].name,
  },
  {
    id: '10',
    name: 'Inorganic Chemistry',
    deleted: false,
    creationDate: '',
    subject: subjects[2],
    subjectId: subjects[2].id,
    subjectName: subjects[2].name,
  },
  {
    id: '11',
    name: 'Physical Chemistry',
    deleted: false,
    creationDate: '',
    subject: subjects[2],
    subjectId: subjects[2].id,
    subjectName: subjects[2].name,
  },
  {
    id: '12',
    name: 'Biochemistry',
    deleted: false,
    creationDate: '',
    subject: subjects[2],
    subjectId: subjects[2].id,
    subjectName: subjects[2].name,
  },
  {
    id: '13',
    name: 'Zoology',
    deleted: false,
    creationDate: '',
    subject: subjects[3],
    subjectId: subjects[3].id,
    subjectName: subjects[3].name,
  },
  {
    id: '14',
    name: 'Botany',
    deleted: false,
    creationDate: '',
    subject: subjects[3],
    subjectId: subjects[3].id,
    subjectName: subjects[3].name,
  },
  {
    id: '15',
    name: 'Genetics',
    deleted: false,
    creationDate: '',
    subject: subjects[3],
    subjectId: subjects[3].id,
    subjectName: subjects[3].name,
  },
  {
    id: '16',
    name: 'Ecology',
    deleted: false,
    creationDate: '',
    subject: subjects[3],
    subjectId: subjects[3].id,
    subjectName: subjects[3].name,
  },
]
